

ALTER TABLE players
    ADD COLUMN IF NOT EXISTS energy_max INT NOT NULL DEFAULT 240,
    ADD COLUMN IF NOT EXISTS energy INT NOT NULL DEFAULT 240,
    ADD COLUMN IF NOT EXISTS energy_last_reset DATE DEFAULT CURRENT_DATE;