ALTER TABLE items
ADD COLUMN IF NOT EXISTS slot TEXT DEFAULT NULL;

ALTER TABLE items
ADD COLUMN IF NOT EXISTS atk INTEGER DEFAULT 0;

ALTER TABLE items
ADD COLUMN IF NOT EXISTS defense INTEGER DEFAULT 0;

ALTER TABLE items
ADD COLUMN IF NOT EXISTS hp INTEGER DEFAULT 0;

ALTER TABLE items
ADD COLUMN IF NOT EXISTS mp INTEGER DEFAULT 0;

ALTER TABLE items
ADD COLUMN IF NOT EXISTS level_req INTEGER DEFAULT 1;

ALTER TABLE items
ADD COLUMN IF NOT EXISTS class_req TEXT DEFAULT NULL;

-- таймстемпи
ALTER TABLE items
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();

ALTER TABLE items
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- якщо хочеш — видаляємо зайве
ALTER TABLE items
DROP COLUMN IF EXISTS category;