ALTER TABLE items
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS slot        TEXT,
    ADD COLUMN IF NOT EXISTS emoji       TEXT,
    ADD COLUMN IF NOT EXISTS stats       JSONB DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS is_global   BOOLEAN DEFAULT FALSE;