INSERT INTO items (
  name, rarity, code, category, descr,
  base_value, stack_max, weight, tradable, bind_on_pickup,
  slot, atk, defense, hp, mp, level_req, class_req,
  is_global, amount, stackable, sell_price, npc_key, is_archived,
  created_at, updated_at
) VALUES
('Бурштин', 'Звичайний', 'ore_gem_burshtyn', 'ore_gem',
'Скам’яніла смола давніх лісів, знайдена в землі біля поховань.',
6, 99, 1, true, false,
NULL, 0, 0, 0, 0, 1, NULL,
false, 1, true, 6, NULL, false,
NOW(), NOW()),

('Кварц', 'Звичайний', 'ore_gem_kvarts', 'ore_gem',
'Поширений мінерал із тріщин землі, використовується для простих виробів.',
5, 99, 1, true, false,
NULL, 0, 0, 0, 0, 1, NULL,
false, 1, true, 5, NULL, false,
NOW(), NOW()),

('Яшма', 'Звичайний', 'ore_gem_yashma', 'ore_gem',
'Щільний камінь різного забарвлення, видобутий у старих шахтах.',
6, 99, 1, true, false,
NULL, 0, 0, 0, 0, 1, NULL,
false, 1, true, 6, NULL, false,
NOW(), NOW()),

('Онікс', 'Добротний', 'ore_gem_oniks', 'ore_gem',
'Темний шаруватий камінь, придатний для різьблення й оздоб.',
12, 99, 1, true, false,
NULL, 0, 0, 0, 0, 3, NULL,
false, 1, true, 12, NULL, false,
NOW(), NOW()),

('Аметист', 'Добротний', 'ore_gem_ametyst', 'ore_gem',
'Фіолетовий кварц, цінний за колір і чистоту.',
14, 99, 1, true, false,
NULL, 0, 0, 0, 0, 3, NULL,
false, 1, true, 14, NULL, false,
NOW(), NOW()),

('Гранат', 'Добротний', 'ore_gem_granat', 'ore_gem',
'Червоний самоцвіт із глибоких шарів землі.',
15, 99, 1, true, false,
NULL, 0, 0, 0, 0, 4, NULL,
false, 1, true, 15, NULL, false,
NOW(), NOW()),

('Малахіт', 'Добротний', 'ore_gem_malakhit', 'ore_gem',
'Зелений камінь зі смугастим візерунком.',
16, 99, 1, true, false,
NULL, 0, 0, 0, 0, 4, NULL,
false, 1, true, 16, NULL, false,
NOW(), NOW()),

('Нефрит', 'Рідкісний', 'ore_gem_nefryt', 'ore_gem',
'Щільний і гладкий камінь, важкий у добуванні.',
22, 99, 1, true, false,
NULL, 0, 0, 0, 0, 5, NULL,
false, 1, true, 22, NULL, false,
NOW(), NOW()),

('Сапфір', 'Рідкісний', 'ore_gem_sapfir', 'ore_gem',
'Синій дорогоцінний камінь.',
26, 99, 1, true, false,
NULL, 0, 0, 0, 0, 6, NULL,
false, 1, true, 26, NULL, false,
NOW(), NOW()),

('Рубін', 'Рідкісний', 'ore_gem_rubin', 'ore_gem',
'Яскраво-червоний дорогоцінний камінь.',
28, 99, 1, true, false,
NULL, 0, 0, 0, 0, 6, NULL,
false, 1, true, 28, NULL, false,
NOW(), NOW()),

('Опал', 'Вибраний', 'ore_gem_opal', 'ore_gem',
'Камінь із мінливим забарвленням.',
32, 99, 1, true, false,
NULL, 0, 0, 0, 0, 7, NULL,
false, 1, true, 32, NULL, false,
NOW(), NOW()),

('Смарагд', 'Вибраний', 'ore_gem_smarahd', 'ore_gem',
'Зелений дорогоцінний камінь.',
35, 99, 1, true, false,
NULL, 0, 0, 0, 0, 8, NULL,
false, 1, true, 35, NULL, false,
NOW(), NOW()),

('Гірський кришталь', 'Обереговий', 'ore_gem_hirskyi_kryshtal', 'ore_gem',
'Прозорий кварц, який часто клали до поховань.',
40, 99, 1, true, false,
NULL, 0, 0, 0, 0, 9, NULL,
false, 1, true, 40, NULL, false,
NOW(), NOW()),

('Алмаз', 'Божественний', 'ore_gem_almaz', 'ore_gem',
'Надзвичайно твердий і рідкісний камінь.',
60, 20, 1, true, false,
NULL, 0, 0, 0, 0, 10, NULL,
false, 1, true, 60, NULL, false,
NOW(), NOW())

ON CONFLICT (code) DO NOTHING;